# SEE: https://github.com/andri-andreal/docker-bun-postgres/blob/main/docker-compose.yml
version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: ./install/bun/Dockerfile
    init: true
    ulimits:
      memlock: -1
    ports:
      - "8080:8080"
    volumes:
      - ./code:/home/bun/app
    command: ["bun", "--watch", "./src/index.ts"]
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./install/db/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: